# Generated by Django 6.1 on 2026-09-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noodles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noodle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='noodles.category'),
        ),
    ]
